# THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
# BASED ON c:\Users\This PC\STM32CubeIDE\VER_100\APPLICATION_NEW_FORMAT

function(add_st_target_properties TARGET_NAME)

target_compile_definitions(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:DEBUG>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:STM32L152xC>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:USE_HAL_DRIVER>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:STM32L152xC>"
)

target_include_directories(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/THT_Libraries\\Low Libraries>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/THT_Libraries\\Middle Libraries>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L1xx_HAL_Driver\\Inc>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L1xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32L1xx\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\Target>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\App>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FatFs\\src>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Core\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L1xx_HAL_Driver\\Inc>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\STM32L1xx_HAL_Driver\\Inc\\Legacy>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Device\\ST\\STM32L1xx\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Drivers\\CMSIS\\Include>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\Target>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/FATFS\\App>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:${PROJECT_SOURCE_DIR}/Middlewares\\Third_Party\\FatFs\\src>"
)

target_compile_options(
    ${TARGET_NAME} PRIVATE
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:ASM>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-g3>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:-g3>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:ASM>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-g0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-g0>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:-O0>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:-Os>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:-Os>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<CONFIG:Debug>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:C>>:>"
    "$<$<AND:$<NOT:$<CONFIG:Debug>>,$<COMPILE_LANGUAGE:CXX>>:>"
    "$<$<CONFIG:Debug>:-mcpu=cortex-m3>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m3>"
)

target_link_libraries(
    ${TARGET_NAME} PRIVATE
)

target_link_directories(
    ${TARGET_NAME} PRIVATE
)

target_link_options(
    ${TARGET_NAME} PRIVATE
    "$<$<CONFIG:Debug>:-mcpu=cortex-m3>"
    "$<$<NOT:$<CONFIG:Debug>>:-mcpu=cortex-m3>"
    -T
    "$<$<CONFIG:Debug>:${PROJECT_SOURCE_DIR}/STM32L152CCTX_FLASH.ld>"
    "$<$<NOT:$<CONFIG:Debug>>:${PROJECT_SOURCE_DIR}/STM32L152CCTX_FLASH.ld>"
)

target_sources(
    ${TARGET_NAME} PRIVATE
    "THT_Libraries\\Low Libraries\\battery.c"
    "THT_Libraries\\Low Libraries\\bq2429x.c"
    "THT_Libraries\\Low Libraries\\fatfs_sd.c"
    "THT_Libraries\\Low Libraries\\rainfall.c"
    "THT_Libraries\\Low Libraries\\sd.c"
    "THT_Libraries\\Low Libraries\\sim7600.c"
    "THT_Libraries\\Middle Libraries\\clock.c"
    "THT_Libraries\\Middle Libraries\\dev_config.c"
    "THT_Libraries\\Middle Libraries\\fota.c"
    "THT_Libraries\\Middle Libraries\\http.c"
    "THT_Libraries\\Middle Libraries\\level_sensor.c"
    "THT_Libraries\\Middle Libraries\\power.c"
    "THT_Libraries\\Middle Libraries\\sdcard.c"
    "THT_Libraries\\Middle Libraries\\sim.c"
    "THT_Libraries\\Middle Libraries\\sms.c"
    "THT_Libraries\\Middle Libraries\\telegram.c"
    "THT_Libraries\\Middle Libraries\\wlv_def.c"
    "Core\\Inc\\logger.c"
    "Core\\Src\\main.c"
    "Core\\Src\\stm32l1xx_hal_msp.c"
    "Core\\Src\\stm32l1xx_it.c"
    "Core\\Src\\syscalls.c"
    "Core\\Src\\sysmem.c"
    "Core\\Src\\system_stm32l1xx.c"
    "Core\\Startup\\startup_stm32l152cctx.s"
    "FATFS\\App\\fatfs.c"
    "FATFS\\Target\\user_diskio.c"
    "Middlewares\\Third_Party\\FatFs\\src\\diskio.c"
    "Middlewares\\Third_Party\\FatFs\\src\\ff_gen_drv.c"
    "Middlewares\\Third_Party\\FatFs\\src\\ff.c"
    "Middlewares\\Third_Party\\FatFs\\src\\option\\ccsbcs.c"
    "Middlewares\\Third_Party\\FatFs\\src\\option\\syscall.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_adc_ex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_adc.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_cortex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_crc.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_dma.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_exti.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_flash_ex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_flash_ramfunc.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_flash.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_gpio.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_i2c.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_pwr_ex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_pwr.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_rcc_ex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_rcc.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_rtc_ex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_rtc.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_spi.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_tim_ex.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_tim.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal_uart.c"
    "Drivers\\STM32L1xx_HAL_Driver\\Src\\stm32l1xx_hal.c"
    "VRAIN\\APPLICATION\\FUNCTIONS\\rain_function.c"
    "VRAIN\\DRIVERS\\BQ2429x\\bq24298.c"
    "VRAIN\\DRIVERS\\FLASH\\flash.c"
    "VRAIN\\DRIVERS\\LOG\\logger.c"
    "VRAIN\\DRIVERS\\SDCARD\\fatfs_sd.c"
    "VRAIN\\DRIVERS\\SDCARD\\sd.c"
    "VRAIN\\DRIVERS\\SIM7x00\\sim7x00.c"
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${TARGET_NAME}>
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O ihex
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.hex
)

add_custom_command(
    TARGET ${TARGET_NAME} POST_BUILD
    COMMAND ${CMAKE_OBJCOPY} -O binary
    $<TARGET_FILE:${TARGET_NAME}> ${TARGET_NAME}.bin
)

endfunction()