/*
 * bq2429x.h
 *
 *  Created on: May 4, 2023
 *      Author: Binh Hoang
 */

#ifndef LOW_LIBRARIES_BQ2429X_H_
#define LOW_LIBRARIES_BQ2429X_H_

#include "wlv_def.h"
#include "power.h"

#define BQ_I2C_ADDRESS					0xD6 //0x6B << 1
/*!
 * ============================================================================
 * BQ24298 Internal registers Address
 * ============================================================================
 */
/* Config and Control */
#define REG_INPUT_SOURCE				0x00
#define REG_POWER_ONCFG					0x01
#define REG_CHARGE_CURRENT				0x02
#define REG_IPRECHG_ITERM				0x03
#define REG_CHARGE_VOLTAGE				0x04
#define REG_CHARGETERM_TIMER			0x05
#define REG_BOOSTV_TREG					0x06
#define REG_MISC_OPERATION				0x07

/* Status */
#define REG_SYSTEMSTATUS				0x08
#define REG_NEWFAULT					0x09
#define REG_VENDER_PART_REVISION		0x0A

/*!
 * ============================================================================
 * BQ24298 LoRa bits control definition
 * ============================================================================
 */

/*!
 * REG_INPUT_SOURCE
 */
#define BQ_INPUT_SOURCE_EN_HIZ_Pos				7u
#define BQ_INPUT_SOURCE_EN_HIZ_Msk				(0x01 << BQ_INPUT_SOURCE_EN_HIZ_Pos)
#define BQ_INPUT_SOURCE_EN_HIZ_DISABLE			(0x00 << BQ_INPUT_SOURCE_EN_HIZ_Pos)
#define BQ_INPUT_SOURCEEN_HIZ_ENABLE			(0x01 << BQ_INPUT_SOURCE_EN_HIZ_Pos)

#define BQ_INPUT_SOURCE_VINDPM_Pos				3u
#define BQ_INPUT_SOURCE_VINDPM_Msk				(0x0F << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_3_88_V			(0x00 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_3_96_V			(0x01 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_04_V			(0x02 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_12_V			(0x03 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_20_V			(0x04 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_28_V			(0x05 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_36_V			(0x06 << BQ_INPUT_SOURCE_VINDPM_Pos) //Default
#define BQ_INPUT_SOURCE_VINDPM_4_44_V			(0x07 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_52_V			(0x08 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_60_V			(0x09 << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_68_V			(0x0A << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_76_V			(0x0B << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_84_V			(0x0C << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_4_92_V			(0x0D << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_5_00_V			(0x0E << BQ_INPUT_SOURCE_VINDPM_Pos)
#define BQ_INPUT_SOURCE_VINDPM_5_08_V			(0x0F << BQ_INPUT_SOURCE_VINDPM_Pos)

#define BQ_INPUT_SOURCE_IINLIM_Pos				0u
#define BQ_INPUT_SOURCE_IINLIM_Msk				(0x07 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_0100_MA			(0x00 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_0150_MA			(0x01 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_0500_MA			(0x02 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_0900_MA			(0x03 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_1000_MA			(0x04 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_1500_MA			(0x05 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_2000_MA			(0x06 << BQ_INPUT_SOURCE_IINLIM_Pos)
#define BQ_INPUT_SOURCE_IINLIM_3000_MA			(0x07 << BQ_INPUT_SOURCE_IINLIM_Pos)

/*!
 * REG_POWER_ONCFG
 */
#define BQ_POWER_ONCFG_REGRESET_Pos				7u
#define BQ_POWER_ONCFG_REGRESET_Msk				(0x01 << BQ_POWER_ONCFG_REGRESET_Pos)
#define BQ_POWER_ONCFG_REGRESET_KEEP			(0x00 << BQ_POWER_ONCFG_REGRESET_Pos) //Default
#define BQ_POWER_ONCFG_REGRESET_RESET			(0x01 << BQ_POWER_ONCFG_REGRESET_Pos)

#define BQ_POWER_ONCFG_WDG_Pos					6u
#define BQ_POWER_ONCFG_WDG_Msk					(0x01 << BQ_POWER_ONCFG_WDG_Pos)
#define BQ_POWER_ONCFG_WDG_NORMAL				(0x00 << BQ_POWER_ONCFG_WDG_Pos) //Default
#define BQ_POWER_ONCFG_WDG_RESET				(0x01 << BQ_POWER_ONCFG_WDG_Pos)

#define BQ_POWER_ONCFG_OTG_CONFIG_Pos			5u
#define BQ_POWER_ONCFG_OTG_CONFIG_Msk			(0x01 << BQ_POWER_ONCFG_OTG_CONFIG_Pos)
#define BQ_POWER_ONCFG_OTG_CONFIG_DISABLE		(0x00 << BQ_POWER_ONCFG_OTG_CONFIG_Pos)
#define BQ_POWER_ONCFG_OTG_CONFIG_ENABLE		(0x01 << BQ_POWER_ONCFG_OTG_CONFIG_Pos)

#define BQ_POWER_ONCFG_CHAG_CONFIG_Pos			4u
#define BQ_POWER_ONCFG_CHAG_CONFIG_Msk			(0x01 << BQ_POWER_ONCFG_CHAG_CONFIG_Pos)
#define BQ_POWER_ONCFG_CHAG_CONFIG_DISABLE		(0x00 << BQ_POWER_ONCFG_CHAG_CONFIG_Pos)
#define BQ_POWER_ONCFG_CHAG_CONFIG_ENABLE		(0x01 << BQ_POWER_ONCFG_CHAG_CONFIG_Pos)

#define BQ_POWER_ONCFG_SYS_MIN_Pos				1u
#define BQ_POWER_ONCFG_SYS_MIN_Msk				(0x07 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_0_V			(0x00 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_1_V			(0x01 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_2_V			(0x02 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_3_V			(0x03 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_4_V			(0x04 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_5_V			(0x05 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_6_V			(0x06 << BQ_POWER_ONCFG_SYS_MIN_Pos)
#define BQ_POWER_ONCFG_SYS_MIN_3_7_V			(0x07 << BQ_POWER_ONCFG_SYS_MIN_Pos)

#define BQ_POWER_ONCFG_BOOST_LIM_Pos			0u
#define BQ_POWER_ONCFG_BOOST_LIM_Msk			(0x01 << BQ_POWER_ONCFG_BOOST_LIM_Pos)
#define BQ_POWER_ONCFG_BOOST_LIM_1_A			(0x00 << BQ_POWER_ONCFG_BOOST_LIM_Pos)
#define BQ_POWER_ONCFG_BOOST_LIM_1_5_A			(0x01 << BQ_POWER_ONCFG_BOOST_LIM_Pos)

/*!
 * REG_CHARGE_CURRENT
 */
#define BQ_CHARGE_CURRENT_ICHG_Pos				2u
#define BQ_CHARGE_CURRENT_ICHG_Msk				(0x3F << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0512_MA			(0x00 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0576_MA			(0x01 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0640_MA			(0x02 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0704_MA			(0x03 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0768_MA			(0x04 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0832_MA			(0x05 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0896_MA			(0x06 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_0960_MA			(0x07 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1024_MA			(0x08 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1088_MA			(0x09 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1152_MA			(0x0A << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1216_MA			(0x0B << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1280_MA			(0x0C << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1344_MA			(0x0D << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1408_MA			(0x0E << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1472_MA			(0x0F << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1536_MA          (0x10 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1600_MA          (0x11 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1664_MA          (0x12 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1728_MA          (0x13 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1792_MA          (0x14 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1856_MA          (0x15 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1920_MA          (0x16 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_1984_MA          (0x17 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2048_MA          (0x18 << BQ_CHARGE_CURRENT_ICHG_Pos) //default
#define BQ_CHARGE_CURRENT_ICHG_2112_MA          (0x19 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2176_MA          (0x1A << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2240_MA          (0x1B << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2304_MA          (0x1C << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2368_MA          (0x1D << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2432_MA          (0x1E << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2496_MA          (0x1F << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2560_MA          (0x20 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2624_MA          (0x21 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2688_MA          (0x22 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2752_MA          (0x23 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2816_MA          (0x24 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2880_MA          (0x25 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_2944_MA          (0x26 << BQ_CHARGE_CURRENT_ICHG_Pos)
#define BQ_CHARGE_CURRENT_ICHG_3008_MA          (0x27 << BQ_CHARGE_CURRENT_ICHG_Pos)

#define BQ_CHARGE_BCOLD_Pos						1u
#define BQ_CHARGE_BCOLD_Msk						(0x01 << BQ_CHARGE_BCOLD_Pos)
#define BQ_CHARGE_BCOLD_76_REGN					(0x00 << BQ_CHARGE_BCOLD_Pos) //default
#define BQ_CHARGE_BCOLD_79_REGN					(0x01 << BQ_CHARGE_BCOLD_Pos)

#define BQ_CHARGE_FORCE_20PCT_Pos				0u
#define BQ_CHARGE_FORCE_20PCT_Msk				(0x01 << BQ_CHARGE_FORCE_20PCT_Pos)
#define BQ_CHARGE_FORCE_20PCT_FASTCHAG			(0x00 << BQ_CHARGE_FORCE_20PCT_Pos) //default
#define BQ_CHARGE_FORCE_20PCT_20FASTCHAG		(0x01 << BQ_CHARGE_FORCE_20PCT_Pos)

/* !
 * REG_IPRECHG_ITERM
 */
#define BQ_IPRECHG_ITERM_IPRECHG_Pos			4u
#define BQ_IPRECHG_ITERM_IPRECHG_Msk			(0xF << BQ_IPRECHG_ITERM_IPRECHG_Pos)
//#define BQ_IPRECHG_ITERM_IPRECHG_0128_MA		(0x00 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_0128_MA		(0x01 << BQ_IPRECHG_ITERM_IPRECHG_Pos) //default
#define BQ_IPRECHG_ITERM_IPRECHG_0256_MA		(0x02 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_0384_MA		(0x03 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_0512_MA		(0x04 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_0768_MA		(0x05 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_0896_MA		(0x06 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1024_MA		(0x07 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1152_MA		(0x08 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1280_MA		(0x09 << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1408_MA		(0x0A << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1536_MA		(0x0B << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1664_MA		(0x0C << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1792_MA		(0x0D << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_1920_MA		(0x0E << BQ_IPRECHG_ITERM_IPRECHG_Pos)
#define BQ_IPRECHG_ITERM_IPRECHG_2048_MA		(0x0F << BQ_IPRECHG_ITERM_IPRECHG_Pos)

#define BQ_IPRECHG_ITERM_ITERM_Pos				0u
#define BQ_IPRECHG_ITERM_ITERM_Msk				(0x07 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_128_MA			(0x00 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_256_MA			(0x01 << BQ_IPRECHG_ITERM_ITERM_Pos) //default
#define BQ_IPRECHG_ITERM_ITERM_384_MA			(0x02 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_512_MA			(0x03 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_640_MA			(0x04 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_768_MA			(0x05 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_896_MA			(0x06 << BQ_IPRECHG_ITERM_ITERM_Pos)
#define BQ_IPRECHG_ITERM_ITERM_1024_MA			(0x07 << BQ_IPRECHG_ITERM_ITERM_Pos)

/* !
 * REG_CHARGE_VOLTAGE
 */

#define BQ_CHARGE_VOLTAGE_VREG_Pos				2u
#define BQ_CHARGE_VOLTAGE_VREG_Msk				(0x3F << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3504_MV			(0x00 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3520_MV			(0x01 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3536_MV			(0x02 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3552_MV			(0x03 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3568_MV			(0x04 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3584_MV			(0x05 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3600_MV			(0x06 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3616_MV			(0x07 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3632_MV			(0x08 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3648_MV			(0x09 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3664_MV			(0x0A << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3680_MV			(0x0B << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3696_MV			(0x0C << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3712_MV			(0x0D << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3728_MV			(0x0E << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3744_MV			(0x0F << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3760_MV          (0x10 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3776_MV          (0x11 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3792_MV          (0x12 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3808_MV          (0x13 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3824_MV          (0x14 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3840_MV          (0x15 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3856_MV          (0x16 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3872_MV          (0x17 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3888_MV          (0x18 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3904_MV          (0x19 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3920_MV          (0x1A << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3936_MV          (0x1B << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3952_MV          (0x1C << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3968_MV          (0x1D << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_3984_MV          (0x1E << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4000_MV          (0x1F << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4016_MV          (0x20 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4032_MV          (0x21 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4048_MV          (0x22 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4064_MV          (0x23 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4080_MV          (0x24 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4096_MV          (0x25 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4112_MV          (0x26 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4128_MV          (0x27 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4144_MV          (0x28 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4160_MV          (0x29 << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4176_MV          (0x2A << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4192_MV          (0x2B << BQ_CHARGE_VOLTAGE_VREG_Pos)
#define BQ_CHARGE_VOLTAGE_VREG_4208_MV          (0x2C << BQ_CHARGE_VOLTAGE_VREG_Pos) //default

#define BQ_CHARGE_VOLTAGE_BATLOWV_Pos			1u
#define BQ_CHARGE_VOLTAGE_BATLOWV_Msk			(0x01 << BQ_CHARGE_VOLTAGE_BATLOWV_Pos)
#define BQ_CHARGE_VOLTAGE_BATLOWV_2_8_V			(0x00 << BQ_CHARGE_VOLTAGE_BATLOWV_Pos)
#define BQ_CHARGE_VOLTAGE_BATLOWV_3_0_V			(0x01 << BQ_CHARGE_VOLTAGE_BATLOWV_Pos) //Default

#define BQ_CHARGE_VOLTAGE_VRECHG_Pos			0u
#define BQ_CHARGE_VOLTAGE_VRECHG_Msk			(0x01 << BQ_CHARGE_VOLTAGE_VRECHG_Pos)
#define BQ_CHARGE_VOLTAGE_VRECHG_100_MV			(0x00 << BQ_CHARGE_VOLTAGE_VRECHG_Pos) //Default
#define BQ_CHARGE_VOLTAGE_VRECHG_300_MV			(0x01 << BQ_CHARGE_VOLTAGE_VRECHG_Pos)

/* !
 * REG_CHARGETERM_TIMER
 */
#define BQ_CHARGETERM_TIMER_EN_TERM_Pos			7u
#define BQ_CHARGETERM_TIMER_EN_TERM_Msk			(0x01 << BQ_CHARGETERM_TIMER_EN_TERM_Pos)
#define BQ_CHARGETERM_TIMER_EN_TERM_DISABLE		(0x00 << BQ_CHARGETERM_TIMER_EN_TERM_Pos)
#define BQ_CHARGETERM_TIMER_EN_TERM_ENABLE		(0x01 << BQ_CHARGETERM_TIMER_EN_TERM_Pos) //Default

#define BQ_CHARGETERM_TIMER_BATFET_RST_EN_Pos	6u
#define BQ_CHARGETERM_TIMER_BATFET_RST_EN_Msk		(0x01 << BQ_CHARGETERM_TIMER_BATFET_RST_EN_Pos)
#define BQ_CHARGETERM_TIMER_BATFET_RST_EN_DISABLE	(0x00 << BQ_CHARGETERM_TIMER_BATFET_RST_EN_Pos)
#define BQ_CHARGETERM_TIMER_BATFET_RST_EN_ENABLE	(0x01 << BQ_CHARGETERM_TIMER_BATFET_RST_EN_Pos) //default

#define BQ_CHARGETERM_TIMER_WATCHDOG_Pos		4u
#define BQ_CHARGETERM_TIMER_WATCHDOG_Msk		(0x03 << BQ_CHARGETERM_TIMER_WATCHDOG_Pos)
#define BQ_CHARGETERM_TIMER_WATCHDOG_000_S		(0x00 << BQ_CHARGETERM_TIMER_WATCHDOG_Pos)
#define BQ_CHARGETERM_TIMER_WATCHDOG_040_S		(0x01 << BQ_CHARGETERM_TIMER_WATCHDOG_Pos)  //default
#define BQ_CHARGETERM_TIMER_WATCHDOG_080_S		(0x02 << BQ_CHARGETERM_TIMER_WATCHDOG_Pos)
#define BQ_CHARGETERM_TIMER_WATCHDOG_160_S		(0x03 << BQ_CHARGETERM_TIMER_WATCHDOG_Pos)

#define BQ_CHARGETERM_TIMER_EN_TIMER_Pos		3u
#define BQ_CHARGETERM_TIMER_EN_TIMER_Msk		(0x01 << BQ_CHARGETERM_TIMER_EN_TIMER_Pos)
#define BQ_CHARGETERM_TIMER_EN_TIMER_DISABLE	(0x00 << BQ_CHARGETERM_TIMER_EN_TIMER_Pos)
#define BQ_CHARGETERM_TIMER_EN_TIMER_ENABLE		(0x01 << BQ_CHARGETERM_TIMER_EN_TIMER_Pos) //default

#define BQ_CHARGETERM_TIMER_CHG_TIMER_Pos		0u
#define BQ_CHARGETERM_TIMER_CHG_TIMER_Msk		(0x03 << BQ_CHARGETERM_TIMER_CHG_TIMER_Pos)
#define BQ_CHARGETERM_TIMER_CHG_TIMER_05_HOURS	(0x00 << BQ_CHARGETERM_TIMER_CHG_TIMER_Pos)
#define BQ_CHARGETERM_TIMER_CHG_TIMER_08_HOURS	(0x01 << BQ_CHARGETERM_TIMER_CHG_TIMER_Pos)
#define BQ_CHARGETERM_TIMER_CHG_TIMER_12_HOURS	(0x02 << BQ_CHARGETERM_TIMER_CHG_TIMER_Pos) //default
#define BQ_CHARGETERM_TIMER_CHG_TIMER_20_HOURS	(0x03 << BQ_CHARGETERM_TIMER_CHG_TIMER_Pos)

/* !
 * REG_BOOSTV_TREG
 */
#define BQ_BOOSTV_TREG_BOOSTV_Pos				4u
#define BQ_BOOSTV_TREG_BOOSTV_Msk				(0x0F << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4550_MV			(0x00 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4614_MV			(0x01 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4678_MV			(0x02 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4742_MV			(0x03 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4806_MV			(0x04 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4870_MV			(0x05 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4934_MV			(0x06 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_4998_MV			(0x07 << BQ_BOOSTV_TREG_BOOSTV_Pos)//Default
#define BQ_BOOSTV_TREG_BOOSTV_5062_MV			(0x08 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5126_MV			(0x09 << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5190_MV			(0x0A << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5254_MV			(0x0B << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5318_MV			(0x0C << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5382_MV			(0x0D << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5446_MV			(0x0E << BQ_BOOSTV_TREG_BOOSTV_Pos)
#define BQ_BOOSTV_TREG_BOOSTV_5510_MV			(0x0F << BQ_BOOSTV_TREG_BOOSTV_Pos)

#define BQ_BOOSTV_TREG_BHOT_Pos					2u
#define BQ_BOOSTV_TREG_BHOT_Msk					(0x03 << BQ_BOOSTV_TREG_BHOT_Pos)
#define BQ_BOOSTV_TREG_BHOT_33_REGN				(0x00 << BQ_BOOSTV_TREG_BHOT_Pos) //Default
#define BQ_BOOSTV_TREG_BHOT_36_REGN				(0x01 << BQ_BOOSTV_TREG_BHOT_Pos)
#define BQ_BOOSTV_TREG_BHOT_30_REGN				(0x02 << BQ_BOOSTV_TREG_BHOT_Pos)
#define BQ_BOOSTV_TREG_BHOT_DISABLE				(0x03 << BQ_BOOSTV_TREG_BHOT_Pos)

#define BQ_BOOSTV_TREG_TREG_Pos					0u
#define BQ_BOOSTV_TREG_TREG_Msk					(0x03 << BQ_BOOSTV_TREG_TREG_Pos)
#define BQ_BOOSTV_TREG_TREG_60					(0x00 << BQ_BOOSTV_TREG_TREG_Pos)
#define BQ_BOOSTV_TREG_TREG_80					(0x01 << BQ_BOOSTV_TREG_TREG_Pos)
#define BQ_BOOSTV_TREG_TREG_100					(0x02 << BQ_BOOSTV_TREG_TREG_Pos)
#define BQ_BOOSTV_TREG_TREG_120					(0x03 << BQ_BOOSTV_TREG_TREG_Pos)//Default

/* !
 * REG_MISC_OPERATION
 */
#define BQ_MISC_OPERATION_DPDM_EN_Pos			7u
#define BQ_MISC_OPERATION_DPDM_EN_Msk			(0x01 << BQ_MISC_OPERATION_DPDM_EN_Pos)
#define BQ_MISC_OPERATION_DPDM_EN_DISABLE		(0x00 << BQ_MISC_OPERATION_DPDM_EN_Pos) //Default value       
#define BQ_MISC_OPERATION_DPDM_EN_ENABLE		(0x01 << BQ_MISC_OPERATION_DPDM_EN_Pos)

#define BQ_MISC_OPERATION_TMR2X_EN_Pos			6u
#define BQ_MISC_OPERATION_TMR2X_EN_Msk			(0x01 << BQ_MISC_OPERATION_TMR2X_EN_Pos)
#define BQ_MISC_OPERATION_TMR2X_EN_DISABLE		(0x00 << BQ_MISC_OPERATION_TMR2X_EN_Pos)
#define BQ_MISC_OPERATION_TMR2X_EN_ENABLE		(0x01 << BQ_MISC_OPERATION_TMR2X_EN_Pos) //Default

#define BQ_MISC_OPERATION_BATFET_DISABLE_Pos	5u
#define BQ_MISC_OPERATION_BATFET_DISABLE_Msk	(0x01 << BQ_MISC_OPERATION_BATFET_DISABLE_Pos)
#define BQ_MISC_OPERATION_BATFET_DISABLE_Q4_ON	(0x00 << BQ_MISC_OPERATION_BATFET_DISABLE_Pos) //Default
#define BQ_MISC_OPERATION_BATFET_DISABLE_Q4_OFF	(0x01 << BQ_MISC_OPERATION_BATFET_DISABLE_Pos)

#define BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_Pos	1u
#define BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_Msk	(0x01 << BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_Pos)
#define BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_OFF	(0x00 << BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_Pos)
#define BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_ON	(0x01 << BQ_MISC_OPERATION_INT_MASK_CHAG_FAULT_Pos) //Default

#define BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_Pos	0u
#define BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_Msk	(0x01 << BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_Pos)
#define BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_OFF	(0x00 << BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_Pos)
#define BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_ON		(0x01 << BQ_MISC_OPERATION_INT_MASK_BAT_FAULT_Pos) //Default

/* !
 * REG_SYSTEMSTATUS - Read Only
 */
#define BQ_SYSTEMSTATUS_VBUS_Pos				6u
#define BQ_SYSTEMSTATUS_VBUS_Msk				(0x03 << BQ_SYSTEMSTATUS_VBUS_Pos)
#define BQ_SYSTEMSTATUS_VBUS_UNKOWN				(0x00 << BQ_SYSTEMSTATUS_VBUS_Pos)
#define BQ_SYSTEMSTATUS_VBUS_USB				(0x01 << BQ_SYSTEMSTATUS_VBUS_Pos)
#define BQ_SYSTEMSTATUS_VBUS_ADAPTER			(0x02 << BQ_SYSTEMSTATUS_VBUS_Pos)
#define BQ_SYSTEMSTATUS_VBUS_OTG				(0x03 << BQ_SYSTEMSTATUS_VBUS_Pos)

#define BQ_SYSTEMSTATUS_CHRG_Pos				4u
#define BQ_SYSTEMSTATUS_CHRG_Msk				(0x03 << BQ_SYSTEMSTATUS_CHRG_Pos)
#define BQ_SYSTEMSTATUS_CHRG_NOT_CHRG			(0x00 << BQ_SYSTEMSTATUS_CHRG_Pos)
#define BQ_SYSTEMSTATUS_CHRG_PRE_CHRG			(0x01 << BQ_SYSTEMSTATUS_CHRG_Pos)
#define BQ_SYSTEMSTATUS_CHRG_FAST_CHRG			(0x02 << BQ_SYSTEMSTATUS_CHRG_Pos)
#define BQ_SYSTEMSTATUS_CHRG_CHRG_TERM			(0x03 << BQ_SYSTEMSTATUS_CHRG_Pos)

#define BQ_SYSTEMSTATUS_DPM_Pos					3u
#define BQ_SYSTEMSTATUS_DPM_Msk					(0x01 << BQ_SYSTEMSTATUS_DPM_Pos)
#define BQ_SYSTEMSTATUS_DPM_NOT_PDM				(0x00 << BQ_SYSTEMSTATUS_DPM_Pos)
#define BQ_SYSTEMSTATUS_DPM_VINPDM_IINPDM		(0x01 << BQ_SYSTEMSTATUS_DPM_Pos)

#define BQ_SYSTEMSTATUS_PG_Pos					2u
#define BQ_SYSTEMSTATUS_PG_Msk					(0x01 << BQ_SYSTEMSTATUS_PG_Pos)
#define BQ_SYSTEMSTATUS_PG_NOT_GOOD				(0x00 << BQ_SYSTEMSTATUS_PG_Pos)
#define BQ_SYSTEMSTATUS_PG_GOOD					(0x01 << BQ_SYSTEMSTATUS_PG_Pos)

#define BQ_SYSTEMSTATUS_THERM_Pos				1u
#define BQ_SYSTEMSTATUS_THERM_Msk				(0x01 << BQ_SYSTEMSTATUS_THERM_Pos)
#define BQ_SYSTEMSTATUS_THERM_NORMAL			(0x00 << BQ_SYSTEMSTATUS_THERM_Pos)
#define BQ_SYSTEMSTATUS_THERM_IN_TREG			(0x01 << BQ_SYSTEMSTATUS_THERM_Pos)

#define BQ_SYSTEMSTATUS_VSYS_Pos				0u
#define BQ_SYSTEMSTATUS_VSYS_Msk				(0x01 << BQ_SYSTEMSTATUS_VSYS_Pos)
#define BQ_SYSTEMSTATUS_VSYS_NOT_VSYSREG		(0x00 << BQ_SYSTEMSTATUS_VSYS_Pos)
#define BQ_SYSTEMSTATUS_VSYS_IN_VSYSREG			(0x01 << BQ_SYSTEMSTATUS_VSYS_Pos)

/* !
 * REG_NEWFAULT - Read Only
 */
#define BQ_NEWFAULT_WATCHDOG_Pos				7u
#define BQ_NEWFAULT_WATCHDOG_Msk				(0x01 << BQ_NEWFAULT_WATCHDOG_Pos)
#define BQ_NEWFAULT_WATCHDOG_NORMAL				(0x00 << BQ_NEWFAULT_WATCHDOG_Pos)
#define BQ_NEWFAULT_WATCHDOG_WDGT_EXPIRATION	(0x01 << BQ_NEWFAULT_WATCHDOG_Pos)

#define BQ_NEWFAULT_OTG_Pos						6u
#define BQ_NEWFAULT_OTG_Msk						(0x01 << BQ_NEWFAULT_OTG_Pos)
#define BQ_NEWFAULT_OTG_NORMAL					(0x00 << BQ_NEWFAULT_OTG_Pos)
#define BQ_NEWFAULT_OTG_FAULT					(0x01 << BQ_NEWFAULT_OTG_Pos)

#define BQ_NEWFAULT_CHRG_Pos					4u
#define BQ_NEWFAULT_CHRG_Msk					(0x03 << BQ_NEWFAULT_CHRG_Pos)
#define BQ_NEWFAULT_CHRG_NORMAL					(0x00 << BQ_NEWFAULT_CHRG_Pos)
#define BQ_NEWFAULT_CHRG_INPUT_FAULT			(0x01 << BQ_NEWFAULT_CHRG_Pos)
#define BQ_NEWFAULT_CHRG_THERMAL_SHUTDOWN		(0x02 << BQ_NEWFAULT_CHRG_Pos)
#define BQ_NEWFAULT_CHRG_CHRG_TIMER_EXPIRATION	(0x03 << BQ_NEWFAULT_CHRG_Pos)

#define BQ_NEWFAULT_BAT_Pos						3u
#define BQ_NEWFAULT_BAT_Msk						(0x01 << BQ_NEWFAULT_BAT_Pos)
#define BQ_NEWFAULT_BAT_NORMAL					(0x00 << BQ_NEWFAULT_BAT_Pos)
#define BQ_NEWFAULT_BAT_OVP						(0x01 << BQ_NEWFAULT_BAT_Pos)

#define BQ_NEWFAULT_NTC_COLD_Pos				1u
#define BQ_NEWFAULT_NTC_COLD_Msk				(0x01 << BQ_NEWFAULT_NTC_COLD_Pos)
#define BQ_NEWFAULT_NTC_COLD_NORMAL				(0x00 << BQ_NEWFAULT_NTC_COLD_Pos)
#define BQ_NEWFAULT_NTC_COLD_COLD				(0x01 << BQ_NEWFAULT_NTC_COLD_Pos)

#define BQ_NEWFAULT_NTC_HOT_Pos					0u
#define BQ_NEWFAULT_NTC_HOT_Msk					(0x01 << BQ_NEWFAULT_NTC_HOT_Pos)
#define BQ_NEWFAULT_NTC_HOT_NORMAL				(0x00 << BQ_NEWFAULT_NTC_HOT_Pos)
#define BQ_NEWFAULT_NTC_HOT_HOT					(0x01 << BQ_NEWFAULT_NTC_HOT_Pos)

/* !
 * REG_VENDER_PART_REVISION - Read Only
 */

typedef struct
{
	I2C_HandleTypeDef *hi2c;
	uint8_t status;
	uint8_t fault;
} BQ24298_HandleTypeDef;

THT_StatusTypeDef BQ_init(BQ24298_HandleTypeDef *const me, uint8_t *pRegister, size_t size);
THT_StatusTypeDef BQ_readStatus(BQ24298_HandleTypeDef *const me);
THT_StatusTypeDef BQ_readFault(BQ24298_HandleTypeDef *const me);
THT_StatusTypeDef BQ_getPowerState(BQ24298_HandleTypeDef *const me);
#endif /* LOW_LIBRARIES_BQ2429X_H_ */
